import { useCallback, useEffect, useState } from "react";
import { SafeMarkdown } from "../components/SafeMarkdown";
import { Link, useSearchParams } from "react-router-dom";

import { compareContracts, getComparison, listContracts } from "../api/client";
import { useAuth } from "../context/AuthContext";
import type {
  AiPerContractNote,
  Contract,
  ContractCompareResponse,
  RankedContract,
  SideBySideRow,
} from "../types/api";

function RiskBadge({ level }: { level: string }) {
  const cls =
    level === "high"
      ? "risk-badge risk-badge--high"
      : level === "low"
        ? "risk-badge risk-badge--low"
        : "risk-badge risk-badge--medium";
  return <span className={cls}>{level}</span>;
}

function ContractCard({
  contract,
  checked,
  onToggle,
  disabled,
}: {
  contract: Contract;
  checked: boolean;
  onToggle: () => void;
  disabled: boolean;
}) {
  const date = new Intl.DateTimeFormat(undefined, { dateStyle: "medium" }).format(
    new Date(contract.created_at),
  );
  return (
    <label className={`compare-card${checked ? " compare-card--selected" : ""}`}>
      <input
        type="checkbox"
        className="compare-card__checkbox"
        checked={checked}
        onChange={onToggle}
        disabled={disabled && !checked}
      />
      <div className="compare-card__body">
        <span className="compare-card__vendor">
          {contract.vendor_name ?? <em>Unknown vendor</em>}
        </span>
        <span className="compare-card__meta">
          {contract.contract_type ? (
            <span className="capitalize">{contract.contract_type}</span>
          ) : (
            <em>—</em>
          )}
          <span className="compare-card__dot" />
          {date}
        </span>
      </div>
      {checked && <span className="compare-card__check" aria-hidden="true">✓</span>}
    </label>
  );
}

function AiAnalysisSection({
  result,
  contracts,
}: {
  result: ContractCompareResponse;
  contracts: Contract[];
}) {
  function vendorOf(contractId: string) {
    return (
      contracts.find((c) => c.id === contractId)?.vendor_name ??
      result.ranked_contracts.find((r) => r.contract_id === contractId)?.vendor_name ??
      "Unknown"
    );
  }

  return (
    <div className="compare-ai">
      <div className="compare-ai__header">
        <div>
          <p className="eyebrow">AI Analysis</p>
          <h2 className="compare-ai__title">Comparison summary</h2>
        </div>
        <span className="review-model-badge">{result.ai_model}</span>
      </div>

      <SafeMarkdown className="compare-ai__summary prose prose--lg">{result.ai_summary}</SafeMarkdown>

      {result.ai_critical_differences.length > 0 && (
        <div className="compare-ai__block">
          <h3 className="compare-ai__block-heading">Critical differences</h3>
          <ul className="compare-ai__list">
            {result.ai_critical_differences.map((d, i) => (
              <li key={i}>{d}</li>
            ))}
          </ul>
        </div>
      )}

      {result.ai_per_contract.length > 0 && (
        <div className="compare-ai__block">
          <h3 className="compare-ai__block-heading">Per-contract assessment</h3>
          <div className="compare-ai__cards">
            {result.ai_per_contract.map((note: AiPerContractNote) => (
              <div key={note.contract_id} className="compare-ai__contract-card">
                <div className="compare-ai__contract-header">
                  <span className="compare-ai__contract-name">{vendorOf(note.contract_id)}</span>
                </div>
                <p className="compare-ai__verdict">{note.verdict}</p>
                {note.strengths.length > 0 && (
                  <div className="compare-ai__pros-cons">
                    <span className="compare-ai__pros-label">Strengths</span>
                    <ul>
                      {note.strengths.map((s, i) => <li key={i}>{s}</li>)}
                    </ul>
                  </div>
                )}
                {note.weaknesses.length > 0 && (
                  <div className="compare-ai__pros-cons compare-ai__pros-cons--weak">
                    <span className="compare-ai__pros-label">Weaknesses</span>
                    <ul>
                      {note.weaknesses.map((w, i) => <li key={i}>{w}</li>)}
                    </ul>
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      )}

      <p className="review-disclaimer" style={{ marginTop: 24 }}>
        {result.ai_model === "placeholder"
          ? "This comparison was generated by a placeholder reviewer and must not be used for board decisions."
          : `This comparison was generated by ${result.ai_model} and must be verified by a qualified human before board action.`}
      </p>
    </div>
  );
}

function CompareResults({
  result,
  contracts,
}: {
  result: ContractCompareResponse;
  contracts: Contract[];
}) {
  function vendorOf(contractId: string) {
    return (
      contracts.find((c) => c.id === contractId)?.vendor_name ??
      result.ranked_contracts.find((r) => r.contract_id === contractId)?.vendor_name ??
      "Unknown"
    );
  }

  const scores = (row: SideBySideRow) =>
    result.ranked_contracts.map((r) => row.scores[r.contract_id] ?? 0);

  const vendorNames = result.ranked_contracts
    .map((r) => r.vendor_name ?? "Unknown")
    .join(" vs. ");

  return (
    <div className="compare-results">
      <div className="compare-results__topbar no-print">
        <p className="compare-results__contracts">{vendorNames}</p>
        <button
          type="button"
          className="button button--secondary review-page__btn"
          onClick={() => window.print()}
        >
          Export as PDF
        </button>
      </div>

      <div className="compare-print-header">
        <p className="eyebrow">Contract comparison</p>
        <h1 className="detail-title">{vendorNames}</h1>
      </div>

      <AiAnalysisSection result={result} contracts={contracts} />

      <div className="compare-divider" />

      <div className="compare-callouts">
        <div className="compare-callout">
          <span className="compare-callout__label">Best overall</span>
          <span className="compare-callout__value">{vendorOf(result.best_overall)}</span>
        </div>
        <div className="compare-callout">
          <span className="compare-callout__label">Lowest risk</span>
          <span className="compare-callout__value">{vendorOf(result.lowest_risk)}</span>
        </div>
        <div className="compare-callout">
          <span className="compare-callout__label">Best value</span>
          <span className="compare-callout__value">{vendorOf(result.best_value)}</span>
        </div>
      </div>

      <section className="compare-section">
        <h3>Rankings</h3>
        <ol className="compare-ranking">
          {result.ranked_contracts.map((r: RankedContract) => (
            <li key={r.contract_id} className="compare-ranking__item">
              <span className="compare-ranking__num">{r.rank}</span>
              <span className="compare-ranking__vendor">
                {r.vendor_name ?? <em>Unknown vendor</em>}
                {r.contract_type ? (
                  <span className="compare-ranking__type capitalize"> · {r.contract_type}</span>
                ) : null}
              </span>
              <span className="compare-ranking__score">{Number(r.total_score)}/100</span>
              <RiskBadge level={r.risk_level} />
            </li>
          ))}
        </ol>
      </section>

      <section className="compare-section">
        <h3>Side-by-side rubric scores</h3>
        <div className="document-table-wrap">
          <table className="rubric-table compare-table">
            <thead>
              <tr>
                <th>Category</th>
                <th>Max</th>
                {result.ranked_contracts.map((r) => (
                  <th key={r.contract_id}>{r.vendor_name ?? "Unknown"}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              {result.side_by_side_table.map((row) => {
                const vals = scores(row);
                const maxVal = Math.max(...vals);
                return (
                  <tr key={row.category}>
                    <td>{row.category}</td>
                    <td className="rubric-table__num">{Number(row.max_score)}</td>
                    {result.ranked_contracts.map((r) => {
                      const val = row.scores[r.contract_id] ?? 0;
                      const isBest = val === maxVal && vals.filter((v) => v === maxVal).length < vals.length;
                      return (
                        <td
                          key={r.contract_id}
                          className={`rubric-table__num${isBest ? " compare-table__best" : ""}`}
                        >
                          {Number(val)}
                        </td>
                      );
                    })}
                  </tr>
                );
              })}
              <tr className="compare-table__total-row">
                <td><strong>Total</strong></td>
                <td className="rubric-table__num">100</td>
                {result.ranked_contracts.map((r) => (
                  <td key={r.contract_id} className="rubric-table__num">
                    <strong>{Number(r.total_score)}</strong>
                  </td>
                ))}
              </tr>
            </tbody>
          </table>
        </div>
      </section>

      {result.key_differences.length > 0 && (
        <section className="compare-section">
          <h3>Score spread by category</h3>
          <ul className="compare-diffs">
            {result.key_differences.map((d, i) => <li key={i}>{d}</li>)}
          </ul>
        </section>
      )}
    </div>
  );
}

export function ContractComparePage() {
  const { user, loading: authLoading, signInWithGoogle, getIdToken } = useAuth();
  const [searchParams] = useSearchParams();
  const savedId = searchParams.get("saved");

  const [contracts, setContracts] = useState<Contract[]>([]);
  const [listLoading, setListLoading] = useState(false);
  const [selectedIds, setSelectedIds] = useState<Set<string>>(new Set());
  const [comparing, setComparing] = useState(false);
  const [result, setResult] = useState<ContractCompareResponse | null>(null);
  const [error, setError] = useState<string | null>(null);

  const load = useCallback(
    async (signal?: AbortSignal) => {
      setListLoading(true);
      try {
        const token = await getIdToken();
        if (savedId) {
          const saved = await getComparison(token, savedId, signal);
          setResult(saved);
        } else {
          const list = await listContracts(token, signal);
          setContracts(list);
        }
      } finally {
        setListLoading(false);
      }
    },
    [getIdToken, savedId],
  );

  useEffect(() => {
    if (!user) return;
    const controller = new AbortController();
    load(controller.signal).catch((err: unknown) => {
      if (err instanceof DOMException && err.name === "AbortError") return;
      setError(err instanceof Error ? err.message : "Could not load data");
    });
    return () => controller.abort();
  }, [user, load]);

  function toggle(id: string) {
    setSelectedIds((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });
    setResult(null);
  }

  async function handleCompare() {
    setComparing(true);
    setError(null);
    setResult(null);
    try {
      const token = await getIdToken();
      const res = await compareContracts(token, { contract_ids: Array.from(selectedIds) });
      setResult(res);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Comparison failed");
    } finally {
      setComparing(false);
    }
  }

  if (authLoading) {
    return <main className="documents-page">Checking your account…</main>;
  }

  if (!user) {
    return (
      <main className="documents-page documents-page--centered">
        <p className="eyebrow">Contract comparison</p>
        <h1 className="page-title">Sign in to compare contracts.</h1>
        <button
          className="button button--primary"
          type="button"
          onClick={() => void signInWithGoogle()}
        >
          Continue with Google
        </button>
      </main>
    );
  }

  // Saved comparison view: load result directly, no selection UI
  if (savedId) {
    return (
      <main className="documents-page">
        <Link className="back-link no-print" to="/contracts">
          ← Back to contracts
        </Link>
        {listLoading ? (
          <p className="empty-state">Loading saved comparison…</p>
        ) : error ? (
          <div className="document-error" role="alert">{error}</div>
        ) : result ? (
          <CompareResults result={result} contracts={contracts} />
        ) : null}
      </main>
    );
  }

  const atMax = selectedIds.size >= 5;
  const canCompare = selectedIds.size >= 2;

  return (
    <main className="documents-page">
      <Link className="back-link no-print" to="/contracts">
        ← Back to contracts
      </Link>

      <div className="page-heading no-print">
        <div>
          <p className="eyebrow">Contract comparison</p>
          <h1 className="page-title">Compare contracts.</h1>
        </div>
        <p className="page-copy">
          Select 2 to 5 reviewed contracts. The AI will read each contract in full and
          produce a board-ready comparison.
        </p>
      </div>

      <div className="compare-select-panel no-print">
        <div className="compare-select-panel__header">
          <h2>Select contracts</h2>
          <span className="compare-select-panel__count">
            {selectedIds.size} / 5 selected
          </span>
        </div>

        {listLoading ? (
          <p className="empty-state">Loading contracts…</p>
        ) : contracts.length === 0 ? (
          <p className="empty-state">
            No reviewed contracts yet.{" "}
            <Link className="inline-link" to="/contracts">
              Review a contract first.
            </Link>
          </p>
        ) : (
          <div className="compare-card-list">
            {contracts.map((c) => (
              <ContractCard
                key={c.id}
                contract={c}
                checked={selectedIds.has(c.id)}
                onToggle={() => toggle(c.id)}
                disabled={atMax}
              />
            ))}
          </div>
        )}

        {atMax && (
          <p className="compare-select-panel__hint">
            Maximum of 5 contracts per comparison.
          </p>
        )}

        {error ? (
          <div className="document-error" role="alert" style={{ marginTop: 16 }}>
            {error}
          </div>
        ) : null}

        <div className="compare-select-panel__footer">
          <button
            type="button"
            className="button button--primary"
            disabled={!canCompare || comparing}
            onClick={() => void handleCompare()}
          >
            {comparing
              ? "Comparing…"
              : canCompare
                ? `Compare ${selectedIds.size} contracts`
                : "Select at least 2 contracts"}
          </button>
          {comparing && (
            <p className="compare-select-panel__hint">
              Reading contract texts and generating AI analysis — this may take 15–30 seconds.
            </p>
          )}
        </div>
      </div>

      {result ? (
        <CompareResults result={result} contracts={contracts} />
      ) : null}
    </main>
  );
}
