import { type FormEvent, useCallback, useEffect, useState } from "react";

import {
  getContractReview,
  listContracts,
  listDocuments,
  reviewContract,
} from "../api/client";
import { useAuth } from "../context/AuthContext";
import type {
  Contract,
  ContractReview,
  ContractRiskFlag,
  ContractRubricScore,
  Document,
} from "../types/api";

function RiskBadge({ level }: { level: string }) {
  const cls =
    level === "high"
      ? "risk-badge risk-badge--high"
      : level === "low"
        ? "risk-badge risk-badge--low"
        : "risk-badge risk-badge--medium";
  return <span className={cls}>{level}</span>;
}

function ScoreBar({ score, max }: { score: number; max: number }) {
  const pct = Math.round((score / max) * 100);
  return (
    <div className="score-bar">
      <div className="score-bar__fill" style={{ width: `${pct}%` }} />
    </div>
  );
}

function RubricTable({ scores }: { scores: ContractRubricScore[] }) {
  return (
    <table className="rubric-table">
      <thead>
        <tr>
          <th>Category</th>
          <th>Score</th>
          <th>Max</th>
          <th className="rubric-table__bar-col" aria-label="Score bar" />
          <th>Notes</th>
        </tr>
      </thead>
      <tbody>
        {scores.map((s) => (
          <tr key={s.id}>
            <td>{s.category}</td>
            <td className="rubric-table__num">{Number(s.score)}</td>
            <td className="rubric-table__num">{Number(s.max_score)}</td>
            <td>
              <ScoreBar score={Number(s.score)} max={Number(s.max_score)} />
            </td>
            <td className="rubric-table__explanation">{s.explanation}</td>
          </tr>
        ))}
      </tbody>
    </table>
  );
}

function RiskFlags({ flags }: { flags: ContractRiskFlag[] }) {
  if (flags.length === 0) return null;
  return (
    <div className="risk-flags">
      {flags.map((f) => (
        <div
          key={f.id}
          className={`risk-flag risk-flag--${f.severity}`}
        >
          <div className="risk-flag__header">
            <span className="risk-flag__type">{f.risk_type}</span>
            <RiskBadge level={f.severity} />
          </div>
          <p className="risk-flag__explanation">{f.explanation}</p>
          {f.suggested_fix ? (
            <p className="risk-flag__fix">
              <strong>Suggested fix:</strong> {f.suggested_fix}
            </p>
          ) : null}
        </div>
      ))}
    </div>
  );
}

function ReviewPanel({ review }: { review: ContractReview }) {
  const totalScore = Number(review.total_score);
  const isFake = review.model_name === "placeholder";
  return (
    <div className="review-panel">
      <div className="review-panel__header">
        <div className="review-panel__score">
          <span className="review-panel__score-value">{totalScore}</span>
          <span className="review-panel__score-denom">/100</span>
        </div>
        <RiskBadge level={review.risk_level} />
        <span className="review-model-badge">
          {isFake ? "Placeholder reviewer" : review.model_name}
        </span>
      </div>

      <section className="review-section">
        <h3>Executive summary</h3>
        <p>{review.executive_summary}</p>
      </section>

      <section className="review-section">
        <h3>Recommendation</h3>
        <p className="review-recommendation">{review.recommendation}</p>
      </section>

      <section className="review-section">
        <h3>Rubric scores</h3>
        <RubricTable scores={review.rubric_scores} />
      </section>

      {review.risk_flags.length > 0 ? (
        <section className="review-section">
          <h3>Risk flags</h3>
          <RiskFlags flags={review.risk_flags} />
        </section>
      ) : null}

      <p className="review-disclaimer">
        {isFake
          ? "This review was generated by a placeholder reviewer and must not be used for board decisions."
          : `This review was generated by ${review.model_name} and must be verified by a qualified human before board action.`}
      </p>
    </div>
  );
}

function ContractRow({
  contract,
  onSelect,
  selected,
}: {
  contract: Contract;
  onSelect: (id: string) => void;
  selected: boolean;
}) {
  return (
    <tr
      className={`contract-row${selected ? " contract-row--selected" : ""}`}
      onClick={() => onSelect(contract.id)}
      style={{ cursor: "pointer" }}
    >
      <td>{contract.vendor_name ?? <em>Unknown vendor</em>}</td>
      <td className="capitalize">{contract.contract_type ?? <em>—</em>}</td>
      <td>
        <span className="status-pill">{contract.status}</span>
      </td>
      <td>
        {new Intl.DateTimeFormat(undefined, {
          dateStyle: "medium",
          timeStyle: "short",
        }).format(new Date(contract.created_at))}
      </td>
      <td>
        <button
          type="button"
          className="table-action"
          onClick={(e) => {
            e.stopPropagation();
            onSelect(contract.id);
          }}
        >
          {selected ? "Hide review" : "View review"}
        </button>
      </td>
    </tr>
  );
}

export function ContractsPage() {
  const { user, loading: authLoading, signInWithGoogle, getIdToken } = useAuth();
  const [documents, setDocuments] = useState<Document[]>([]);
  const [contracts, setContracts] = useState<Contract[]>([]);
  const [selectedDocumentId, setSelectedDocumentId] = useState("");
  const [vendorName, setVendorName] = useState("");
  const [contractType, setContractType] = useState("");
  const [submitting, setSubmitting] = useState(false);
  const [listLoading, setListLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [selectedContractId, setSelectedContractId] = useState<string | null>(null);
  const [loadedReviews, setLoadedReviews] = useState<Record<string, ContractReview>>({});
  const [reviewLoading, setReviewLoading] = useState(false);

  const processedDocuments = documents.filter((d) => d.status === "processed");

  const refresh = useCallback(
    async (signal?: AbortSignal) => {
      setListLoading(true);
      try {
        const token = await getIdToken();
        const [docs, contractList] = await Promise.all([
          listDocuments(token, signal),
          listContracts(token, signal),
        ]);
        setDocuments(docs);
        setContracts(contractList);
      } finally {
        setListLoading(false);
      }
    },
    [getIdToken],
  );

  useEffect(() => {
    if (!user) {
      setDocuments([]);
      setContracts([]);
      return;
    }
    const controller = new AbortController();
    setError(null);
    refresh(controller.signal).catch((err: unknown) => {
      if (err instanceof DOMException && err.name === "AbortError") return;
      setError(err instanceof Error ? err.message : "Could not load data");
    });
    return () => controller.abort();
  }, [user, refresh]);

  async function handleSelectContract(contractId: string) {
    if (selectedContractId === contractId) {
      setSelectedContractId(null);
      return;
    }
    setSelectedContractId(contractId);
    if (loadedReviews[contractId]) return;

    setReviewLoading(true);
    try {
      const token = await getIdToken();
      const review = await getContractReview(token, contractId);
      setLoadedReviews((prev) => ({ ...prev, [contractId]: review }));
    } catch (err) {
      setError(err instanceof Error ? err.message : "Could not load review");
    } finally {
      setReviewLoading(false);
    }
  }

  async function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    if (!selectedDocumentId) {
      setError("Select");
      return;
    }

    setSubmitting(true);
    setError(null);
    try {
      const token = await getIdToken();
      const result = await reviewContract(token, {
        document_id: selectedDocumentId,
        vendor_name: vendorName.trim() || undefined,
        contract_type: contractType.trim() || undefined,
      });
      setLoadedReviews((prev) => ({ ...prev, [result.contract.id]: result.review }));
      setSelectedContractId(result.contract.id);
      setVendorName("");
      setContractType("");
      setSelectedDocumentId("");
      await refresh();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Review failed");
    } finally {
      setSubmitting(false);
    }
  }

  if (authLoading) {
    return <main className="documents-page">Checking your account…</main>;
  }

  if (!user) {
    return (
      <main className="documents-page documents-page--centered">
        <p className="eyebrow">Contract review</p>
        <h1 className="page-title">Sign in to review HOA contracts.</h1>
        <p className="page-copy">
          Contract reviews are private and scoped to your organization.
        </p>
        <button
          className="button button--primary"
          type="button"
          onClick={() => void signInWithGoogle()}
        >
          Continue with Google
        </button>
      </main>
    );
  }

  return (
    <main className="documents-page">
      <div className="page-heading">
        <div>
          <p className="eyebrow">Contract review</p>
          <h1 className="page-title">Review vendor contracts.</h1>
        </div>
      </div>

      <section className="upload-panel" aria-labelledby="review-heading">
        <div>
          <h2 id="review-heading">New contract review</h2>
          <p>
            Upload and process a contract on the{" "}
            <a href="/documents" className="inline-link">
              Documents page
            </a>{" "}
            first, then select it here.
          </p>
        </div>
        <form className="upload-form" onSubmit={handleSubmit}>
          <label>
            Document
            <select
              value={selectedDocumentId}
              onChange={(e) => setSelectedDocumentId(e.target.value)}
              disabled={submitting}
              required
            >
              <option value="">— select —</option>
              {processedDocuments.map((d) => (
                <option key={d.id} value={d.id}>
                  {d.original_filename}
                </option>
              ))}
            </select>
            {processedDocuments.length === 0 && !listLoading ? (
              <span className="field-hint">
                No processed documents found. Upload and process a contract first.
              </span>
            ) : null}
          </label>
          <label>
            Vendor name <span className="field-optional">(optional)</span>
            <input
              type="text"
              value={vendorName}
              onChange={(e) => setVendorName(e.target.value)}
              placeholder="e.g. ABC Landscaping"
              disabled={submitting}
            />
          </label>
          <label>
            Contract type <span className="field-optional">(optional)</span>
            <input
              type="text"
              value={contractType}
              onChange={(e) => setContractType(e.target.value)}
              placeholder="e.g. landscaping, maintenance, security"
              disabled={submitting}
            />
          </label>
          <button
            className="button button--primary"
            type="submit"
            disabled={submitting || !selectedDocumentId}
          >
            {submitting ? "Reviewing…" : "Review contract"}
          </button>
        </form>
      </section>

      {error ? (
        <div className="document-error" role="alert">
          {error}
        </div>
      ) : null}

      <section className="document-list" aria-labelledby="contracts-heading">
        <div className="document-list__heading">
          <h2 id="contracts-heading">Contract reviews</h2>
          <span>{contracts.length} total</span>
        </div>

        {listLoading ? (
          <p className="empty-state">Loading…</p>
        ) : contracts.length === 0 ? (
          <p className="empty-state">
            No contract reviews yet. Submit the form above to generate the first review.
          </p>
        ) : (
          <div className="document-table-wrap">
            <table className="document-table">
              <thead>
                <tr>
                  <th>Vendor</th>
                  <th>Type</th>
                  <th>Status</th>
                  <th>Reviewed</th>
                  <th aria-label="Actions" />
                </tr>
              </thead>
              <tbody>
                {contracts.map((c) => (
                  <>
                    <ContractRow
                      key={c.id}
                      contract={c}
                      selected={selectedContractId === c.id}
                      onSelect={(id) => void handleSelectContract(id)}
                    />
                    {selectedContractId === c.id ? (
                      <tr key={`${c.id}-review`}>
                        <td colSpan={5} className="review-cell">
                          {reviewLoading && !loadedReviews[c.id] ? (
                            <p className="empty-state">Loading review…</p>
                          ) : loadedReviews[c.id] ? (
                            <ReviewPanel review={loadedReviews[c.id]} />
                          ) : null}
                        </td>
                      </tr>
                    ) : null}
                  </>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </section>
    </main>
  );
}
