import { useEffect, useState } from "react";
import { useParams } from "react-router-dom";

import { getSharedComparison } from "../api/client";
import { SafeMarkdown } from "../components/SafeMarkdown";
import type {
  AiPerContractNote,
  ContractCompareResponse,
  RankedContract,
  SideBySideRow,
} from "../types/api";

function RiskBadge({ level }: { level: string }) {
  const cls =
    level === "high"
      ? "risk-badge risk-badge--high"
      : level === "low"
        ? "risk-badge risk-badge--low"
        : "risk-badge risk-badge--medium";
  return <span className={cls}>{level}</span>;
}

function vendorOf(result: ContractCompareResponse, contractId: string): string {
  return (
    result.ranked_contracts.find((r) => r.contract_id === contractId)?.vendor_name ?? "Unknown"
  );
}

function AiSection({ result }: { result: ContractCompareResponse }) {
  return (
    <div className="compare-ai">
      <div className="compare-ai__header">
        <div>
          <p className="eyebrow">AI Analysis</p>
          <h2 className="compare-ai__title">Comparison summary</h2>
        </div>
        <span className="review-model-badge">{result.ai_model}</span>
      </div>

      <SafeMarkdown className="compare-ai__summary prose prose--lg">
        {result.ai_summary}
      </SafeMarkdown>

      {result.ai_critical_differences.length > 0 && (
        <div className="compare-ai__block">
          <h3 className="compare-ai__block-heading">Critical differences</h3>
          <ul className="compare-ai__list">
            {result.ai_critical_differences.map((d, i) => <li key={i}>{d}</li>)}
          </ul>
        </div>
      )}

      {result.ai_per_contract.length > 0 && (
        <div className="compare-ai__block">
          <h3 className="compare-ai__block-heading">Per-contract assessment</h3>
          <div className="compare-ai__cards">
            {result.ai_per_contract.map((note: AiPerContractNote) => (
              <div key={note.contract_id} className="compare-ai__contract-card">
                <div className="compare-ai__contract-header">
                  <span className="compare-ai__contract-name">
                    {vendorOf(result, note.contract_id)}
                  </span>
                </div>
                <p className="compare-ai__verdict">{note.verdict}</p>
                {note.strengths.length > 0 && (
                  <div className="compare-ai__pros-cons">
                    <span className="compare-ai__pros-label">Strengths</span>
                    <ul>{note.strengths.map((s, i) => <li key={i}>{s}</li>)}</ul>
                  </div>
                )}
                {note.weaknesses.length > 0 && (
                  <div className="compare-ai__pros-cons compare-ai__pros-cons--weak">
                    <span className="compare-ai__pros-label">Weaknesses</span>
                    <ul>{note.weaknesses.map((w, i) => <li key={i}>{w}</li>)}</ul>
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      )}

      <p className="review-disclaimer" style={{ marginTop: 24 }}>
        {result.ai_model === "placeholder"
          ? "This comparison was generated by a placeholder reviewer and must not be used for board decisions."
          : `This comparison was generated by ${result.ai_model} and must be verified by a qualified human before board action.`}
      </p>
    </div>
  );
}

function ComparisonBody({ result }: { result: ContractCompareResponse }) {
  const scores = (row: SideBySideRow) =>
    result.ranked_contracts.map((r) => row.scores[r.contract_id] ?? 0);

  return (
    <div className="compare-results">
      <AiSection result={result} />

      <div className="compare-divider" />

      <div className="compare-callouts">
        <div className="compare-callout">
          <span className="compare-callout__label">Best overall</span>
          <span className="compare-callout__value">{vendorOf(result, result.best_overall)}</span>
        </div>
        <div className="compare-callout">
          <span className="compare-callout__label">Lowest risk</span>
          <span className="compare-callout__value">{vendorOf(result, result.lowest_risk)}</span>
        </div>
        <div className="compare-callout">
          <span className="compare-callout__label">Best value</span>
          <span className="compare-callout__value">{vendorOf(result, result.best_value)}</span>
        </div>
      </div>

      <section className="compare-section">
        <h3>Rankings</h3>
        <ol className="compare-ranking">
          {result.ranked_contracts.map((r: RankedContract) => (
            <li key={r.contract_id} className="compare-ranking__item">
              <span className="compare-ranking__num">{r.rank}</span>
              <span className="compare-ranking__vendor">
                {r.vendor_name ?? <em>Unknown vendor</em>}
                {r.contract_type ? (
                  <span className="compare-ranking__type capitalize"> · {r.contract_type}</span>
                ) : null}
              </span>
              <span className="compare-ranking__score">{Number(r.total_score)}/100</span>
              <RiskBadge level={r.risk_level} />
            </li>
          ))}
        </ol>
      </section>

      <section className="compare-section">
        <h3>Side-by-side rubric scores</h3>
        <div className="document-table-wrap">
          <table className="rubric-table compare-table">
            <thead>
              <tr>
                <th>Category</th>
                <th>Max</th>
                {result.ranked_contracts.map((r) => (
                  <th key={r.contract_id}>{r.vendor_name ?? "Unknown"}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              {result.side_by_side_table.map((row) => {
                const vals = scores(row);
                const maxVal = Math.max(...vals);
                return (
                  <tr key={row.category}>
                    <td>{row.category}</td>
                    <td className="rubric-table__num">{Number(row.max_score)}</td>
                    {result.ranked_contracts.map((r) => {
                      const val = row.scores[r.contract_id] ?? 0;
                      const isBest =
                        val === maxVal && vals.filter((v) => v === maxVal).length < vals.length;
                      return (
                        <td
                          key={r.contract_id}
                          className={`rubric-table__num${isBest ? " compare-table__best" : ""}`}
                        >
                          {Number(val)}
                        </td>
                      );
                    })}
                  </tr>
                );
              })}
              <tr className="compare-table__total-row">
                <td><strong>Total</strong></td>
                <td className="rubric-table__num">100</td>
                {result.ranked_contracts.map((r) => (
                  <td key={r.contract_id} className="rubric-table__num">
                    <strong>{Number(r.total_score)}</strong>
                  </td>
                ))}
              </tr>
            </tbody>
          </table>
        </div>
      </section>

      {result.key_differences.length > 0 && (
        <section className="compare-section">
          <h3>Score spread by category</h3>
          <ul className="compare-diffs">
            {result.key_differences.map((d, i) => <li key={i}>{d}</li>)}
          </ul>
        </section>
      )}
    </div>
  );
}

export function SharedComparisonPage() {
  const { token } = useParams<{ token: string }>();
  const [result, setResult] = useState<ContractCompareResponse | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!token) return;
    const controller = new AbortController();
    setLoading(true);
    getSharedComparison(token, controller.signal)
      .then(setResult)
      .catch((err: unknown) => {
        if (err instanceof DOMException && err.name === "AbortError") return;
        setError(err instanceof Error ? err.message : "Could not load comparison");
      })
      .finally(() => setLoading(false));
    return () => controller.abort();
  }, [token]);

  if (loading) {
    return <main className="documents-page"><p className="empty-state">Loading…</p></main>;
  }

  if (error || !result) {
    return (
      <main className="documents-page">
        <div className="document-error" role="alert">{error ?? "Comparison not found."}</div>
      </main>
    );
  }

  const vendorNames = result.ranked_contracts.map((r) => r.vendor_name ?? "Unknown").join(" vs. ");

  return (
    <main className="documents-page">
      <div className="compare-results__topbar no-print">
        <div>
          <span className="shared-badge">Shared view · read only</span>
          <p className="compare-results__contracts">{vendorNames}</p>
        </div>
        <button
          type="button"
          className="button button--secondary review-page__btn"
          onClick={() => window.print()}
        >
          Export as PDF
        </button>
      </div>

      <div className="compare-print-header">
        <p className="eyebrow">Contract comparison</p>
        <h1 className="detail-title">{vendorNames}</h1>
      </div>

      <ComparisonBody result={result} />
    </main>
  );
}
