import json
from typing import Literal

from pydantic import BaseModel, Field, ValidationError

from app.ai.providers.base import AIProvider
from app.ai.providers.openrouter_provider import AIProviderError

_MAX_TEXT_CHARS = 14_000

_SYSTEM_PROMPT = (
    "You are an expert HOA contract reviewer. "
    "Your entire response must be a single valid JSON object. "
    "Do not include any text before or after the JSON. "
    "Do not use markdown code blocks."
)

_USER_PROMPT_TEMPLATE = """\
Analyze the HOA vendor contract below and return a JSON review.

Contract context:
- Vendor: {vendor_name}
- Contract type: {contract_type}

Score exactly these 5 rubric categories:
1. "Price / Value"       — max 20 points
2. "Scope Clarity"       — max 15 points
3. "Term / Cancellation" — max 15 points
4. "Liability / Insurance" — max 15 points
5. "Payment Terms"       — max 10 points

Required JSON schema (fill every field):
{{
  "executive_summary": "<2–4 sentence summary of the contract and key findings>",
  "recommendation": "<board action recommendation>",
  "risk_level": "low" | "medium" | "high",
  "total_score": <integer 0–100>,
  "rubric_scores": [
    {{
      "category": "<category name>",
      "score": <integer>,
      "max_score": <integer>,
      "explanation": "<1–2 sentence explanation>",
      "citation": "<direct quote from the contract text, or null>"
    }}
  ],
  "risk_flags": [
    {{
      "risk_type": "<short name for the risk>",
      "severity": "low" | "medium" | "high",
      "explanation": "<explanation of the risk>",
      "citation": "<direct quote from the contract text, or null>",
      "suggested_fix": "<negotiation suggestion, or null>"
    }}
  ]
}}

CONTRACT TEXT:
{contract_text}
"""


class RubricScoreResult(BaseModel):
    category: str
    score: int = Field(ge=0)
    max_score: int = Field(ge=1)
    explanation: str
    citation: str | None = None


class RiskFlagResult(BaseModel):
    risk_type: str
    severity: Literal["low", "medium", "high"]
    explanation: str
    citation: str | None = None
    suggested_fix: str | None = None


class ContractReviewResult(BaseModel):
    executive_summary: str
    recommendation: str
    risk_level: Literal["low", "medium", "high"]
    total_score: int = Field(ge=0, le=100)
    rubric_scores: list[RubricScoreResult] = Field(min_length=1)
    risk_flags: list[RiskFlagResult]


class ContractReviewError(Exception):
    """Raised when the AI agent cannot produce a valid review."""


_FAKE_RESULT = ContractReviewResult(
    executive_summary=(
        "This is a placeholder review generated by the fake reviewer. "
        "The contract appears to be a standard service agreement with moderate risk. "
        "Key areas requiring board attention include the termination clause, "
        "the vendor liability cap, and the annual price escalation terms."
    ),
    recommendation=(
        "Conditionally approve pending negotiation of the termination notice period "
        "and the liability cap. Request updated certificates of insurance before signing. "
        "This recommendation is a placeholder and must be replaced by a real AI review "
        "before board use."
    ),
    risk_level="medium",
    total_score=75,
    rubric_scores=[
        RubricScoreResult(
            category="Price / Value",
            score=14,
            max_score=20,
            explanation=(
                "Pricing appears competitive but includes annual escalation clauses "
                "that could increase costs by up to 5% per year without board approval."
            ),
        ),
        RubricScoreResult(
            category="Scope Clarity",
            score=11,
            max_score=15,
            explanation=(
                "The scope of work is generally described but lacks specific performance "
                "standards, response-time guarantees, and measurable service outcomes."
            ),
        ),
        RubricScoreResult(
            category="Term / Cancellation",
            score=10,
            max_score=15,
            explanation=(
                "The contract requires 90 days written notice to terminate, which limits "
                "the HOA's ability to respond quickly to poor vendor performance."
            ),
        ),
        RubricScoreResult(
            category="Liability / Insurance",
            score=11,
            max_score=15,
            explanation=(
                "Vendor carries general liability coverage, but the indemnification clause "
                "is one-sided and the liability cap is set at one month's service fee."
            ),
        ),
        RubricScoreResult(
            category="Payment Terms",
            score=8,
            max_score=10,
            explanation=(
                "Payment terms are standard net-30 with a 1.5% monthly late fee. "
                "No early-payment discounts or disputed-invoice procedures are defined."
            ),
        ),
    ],
    risk_flags=[
        RiskFlagResult(
            risk_type="Excessive Termination Notice",
            severity="medium",
            explanation=(
                "The contract requires 90 days written notice to terminate for convenience. "
                "This significantly limits HOA flexibility to respond to poor vendor performance."
            ),
            suggested_fix=(
                "Negotiate to reduce the termination-for-convenience notice period to 30 days "
                "and add a 10-day termination-for-cause clause."
            ),
        ),
        RiskFlagResult(
            risk_type="Liability Cap Too Low",
            severity="high",
            explanation=(
                "Vendor liability is capped at one month's service fee. This amount is unlikely "
                "to cover property damage, injury, or significant service failures on HOA common areas."
            ),
            suggested_fix=(
                "Request a higher liability cap equal to the total annual contract value. "
                "Verify the vendor carries at least $1M general liability and $500K workers' "
                "compensation coverage and request certificates of insurance."
            ),
        ),
    ],
)


def run_fake_review() -> ContractReviewResult:
    return _FAKE_RESULT


def run_ai_review(
    text_chunks: list[str],
    vendor_name: str | None,
    contract_type: str | None,
    provider: AIProvider,
    model: str,
) -> ContractReviewResult:
    contract_text = "\n\n".join(text_chunks)
    if len(contract_text) > _MAX_TEXT_CHARS:
        contract_text = contract_text[:_MAX_TEXT_CHARS] + "\n[... truncated for length ...]"

    prompt = _USER_PROMPT_TEMPLATE.format(
        vendor_name=vendor_name or "unknown",
        contract_type=contract_type or "general service",
        contract_text=contract_text,
    )

    try:
        raw = provider.complete(
            messages=[
                {"role": "system", "content": _SYSTEM_PROMPT},
                {"role": "user", "content": prompt},
            ],
            model=model,
        )
    except AIProviderError as exc:
        raise ContractReviewError(str(exc)) from exc

    try:
        data = json.loads(raw)
    except json.JSONDecodeError as exc:
        raise ContractReviewError(
            f"Model returned invalid JSON: {exc}. Raw output: {raw[:300]}"
        ) from exc

    try:
        return ContractReviewResult.model_validate(data)
    except ValidationError as exc:
        raise ContractReviewError(
            f"Model output failed schema validation: {exc}"
        ) from exc
